sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sitcomtn-002
env:
  global:
    -
      # LTD_AWS_ID
      secure: EkxVIDa7dmz9pTFhmUWwpsig4icGBUHaAxHW9h01X6g2NOUMP66E0AsJTG2jrKC3mBgyUp9XjfJhgWTgIGv2DQCX+ZASxywEEfo7h+cN1dV0XZrP9J3mSq9vcHrjP/ky6aVj5L6PiDTsHGHrRIVsLwQIozhs9O/mVD9lKRew2St6zh7uFxqkEvbTuEL5SWEiX8nbP+drN7wrn4ifR12kdzPZlCcnxHA1ARQRqPw+aoHtlHKL7kMJSKaEcFwuVOSbOXgaXqovgjVygu5Ou2oPSByrizxFnvj6v3pKR4kfS9XXxkpMOcRhUmNWmWIajV0La+ffQq14etHcK+STRgsaqm8AGn+3yDUKnStBJ+qAr278kvBQZx4mHY+yrnD0XD7UuArr+xwsnq+SGzEnKtsHe0oZCLUXgCRe0Q2wH8YGUDO4xG8IKGcyTcr4SESgE5Tbp5B1TufnvoQLzTPNIXaTz1qaF5MNoLtyQqJ24nCIw6cs6p/o1Ymf6PRC4DPfK/MYda+3EKv0UGsxPJvrIXWAnMIoY75es2Geq8nue0BdpfzUEMlASwp1Stm9DP8pSD+TpPv/mMYxAD366i6hs0syJVJZpftFPnYIwgHCptDF+0uXu60eIXonzKhhy51LR20WNJlUZW0Phb00eP+du1qe+unLxYTOVBBbSASjWuOtVb8=
    -
      # LTD_AWS_SECRET
      secure: bPvnsXskcxgsCaECWNKQ4qgnPCx/qzHtuQHBfD5aBeqVF6RCFP6fzkdAPwOF+DbV2t0EzWlEtaNK4RPmnj+qgMTb7y0xQhsfR/G+KkU2g4Ut8Zdk9bzRJFlC5DV5xoc1DMiiJEs98UDQMbRYa8JTQQBK5K7V1nYgAI7O4CCb0ZpmoBbykxstbtjQIBc+mrZxwA8ymNYpc9Q0LAR7s90NaesqHpiWDvW0ZfLaYYa6LtVLq/tM0Wnrhw93HNEJ8fvhTWURYxVA8m4r+ClOkH21HP/FGmkM7ZtsOmLiL4tC7VTVzaEIFhlADUeR08pgtol0q+j2bytUdgC5BcjL39km+qP2T+sxHy9O6NRKutkIAIGK6CtGFIZ+7L0ppwcDjA2h4ipyo7EJ8JeugLYSi2PA2RSQrvWLJc08oiZepy1u+mbofxTI1Utquacsffm8Dbcov51k+zufCH4y1sskBZg1jMLzOpILoEoXVj6H4EyXeG88l24R0LmzYRg0P93eqxeuEsHrzLxvV4XBrlhLMnwdzmA++HvdBd2tkJcISOYNKRlFGhTraygcJHGdn7pe6FsKl5i6kyGKXt4bbA1WrTKSk258AMXwP/O1rZF7hdKqkO3lUFz4pC28UCMK5vvXoz7C4uyZRD3RSBvzNHsPKbFRcgXJEX035SqM+iZUQuUZt8s=
    -
      # LTD_USERNAME
      secure: R7ZiK7KUzeLBywQ5z4OW3QAwJsJwOpyxrqVtX8KYRJAKgQTzgaMRwL70fWF3r6BSr8Foh3rzOMHYYMUDV1dGSzotgqMMN/9JvB15WiZQf7C9xjj9yb/EmLa+nVieKWTkWiCvMh/jqG1v/yrhit7lss88kfMDyuq6p3kU0w8ZEhCvKstUujWen1m9gaY2sO6x3vBCHBYDqgbAKOfad17OzJovnSdNUEyEf2dVJKu7PijXP+Ewqcu5CogJYxurU24RFVw1kfPoWd8PoLbCSMhBwhMRduMOU33PcIlYYMouSpH+DYzqu4CDu53gmyXU/kgh6z5VHTL2MFhc0P8qNH7j0406ueF9L6Xk9/YzJcEnHOl4AKokTi/BI8eTkUd6rJITiBAdMd898hx6NoeozjEP4oPoNMEYwgot7Rc1Lm7lUx+lD4kjHcHvBPZr5jO9IvmPiMIAaM2CXSSXXbdRHozNHx07PG+yvWLc9VP+jv50+p3XVSW7FZyroHvXvTqU9+mnGWFB3V9fXcVysV+GA78I8ClZytoJPHG8TQDvjRfn8l66mU4oIyMKjR/6zQA7pW37Wihcjp6kIi+2qUGSy8NQRc0wTYmhzChvmiUj9kSMLoeysY8GqilTl1VKZZSK39yFZW6Gd+jbbbj8EMxRU5yxQrk8L2gLfIQS6wujgr5VQsE=
    -
      # LTD_PASSWORD
      secure: Ky9UNw6JSPC7TF7izUhZ6trisXil8rkjqDztz57v194j1hM7Qp9qxvMNUnCl7hvPo+B+eIUK1NHfZNMNwUn2URxaUkpJygueypK3ES0xCFD/AJNVNHe0cRAnxq58OmDPt9ScFe0bR0UXJVGRu8cBjIP0dzKnmtZJohU00aME970ELKG6nuPytZ5rQa3L5u2wLdmExzLJs3oxzFGuhiE7RKN6FDkpsP4fgcPhTR1j+gCUl8VrLv/x8DY02r0o31nc/RXI1eFYeFKkOEjJdzGSHnOS39r6PKOO6o7o+31aXkIFgzHRDgS74gErQhRfXfWFfx71HGZ5VGIa6J27B9M0ZG+tW+F/7kwVgUPfew0aqw9hH2uUiLZhV44MLfT+CLzu+ebzH88YehpUgwT3oUG/ppnUrNdFH8pM/U6xAES6CiaBppGNYYHo0+m2oJVDsRQ+dCwFv/jjjnJz/dY7fksJJt49mX/Vz3B+SZlm6+5LuHpow7QbDTBAQaDGsFUXY5f3aJ5XeYdzJTPoYiewcbdt+zA5E7MlB9qOVbAQ/ELtIiLWIqbTY6karHEsT/24bcHg8ULGGBbnSBNmH9CYfCJqAyORofSvqhCEvUeA70jmPQ42qTbzr0HSFJNsgY6vbX8NBhctiNnGHRCDZC/ZJGVsK8dJ6PNkJab0zhSzxC617Ho=
